version: '3'

services:
  website:
    build: ./website
    container_name: website
#    restart: unless-stopped
#    ports:
#      - "8001:8001"
    depends_on:
      - db
      - chat

  chat:
    build: ./chat
    container_name: chat
#    restart: unless-stopped
    ports:
      - "8000:8000"

  db:
    image: db_image
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: chat_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./dump:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - website
      - chat